language: clojure
lein: lein2
before_script: lein2 with-profile dev javac
script: 
- lein2 with-profile dev,1.7 test
- lein2 clean
- lein2 with-profile dev,1.8 test
jdk:
  # TinkerPop 3 requires JDK 8
  - oraclejdk8
